server:
  port:8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accounting?   useUnicode=true&characterEncoding=utf8
    username: root
    password: 1379Xushichao$
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xushicao.accounting.dao.entity

Accounting:
  logging:
    home: /logs/Accounting
    level: INFO


